// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SmsDeliveryReport_svc.Models
{
    [Table("ShineeDRTransaction", Schema = "SMS")]
    public partial class ShineeDRTransaction
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string ReferenceId { get; set; }
        [StringLength(50)]
        public string MobileNumber { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? SendingStatusUpdateDate { get; set; }
        [StringLength(10)]
        public string Success { get; set; }
        [StringLength(10)]
        public string Fail { get; set; }
        [StringLength(10)]
        public string Block { get; set; }
        [StringLength(10)]
        public string Expired { get; set; }
        [StringLength(10)]
        public string Processing { get; set; }
        [StringLength(10)]
        public string Unknown { get; set; }
        public string XMLResult { get; set; }
        [StringLength(10)]
        public string SendChannel { get; set; }
        [StringLength(10)]
        public string Status { get; set; }
        [StringLength(100)]
        public string Detail { get; set; }
        public DateTime? SendDate { get; set; }
        [StringLength(10)]
        public string DrDate { get; set; }
        public int? Credit { get; set; }
        [StringLength(50)]
        public string FileName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StampDate { get; set; }
        public bool? IsStamp { get; set; }
    }
}